apiVersion: v1
kind: Service
metadata:
  name: tienda-backend
  namespace: user18
spec:
  type: LoadBalancer
  selector:
    app: tienda-backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
