name: CI/CD Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen Docker
        run: |
          docker build -t tienda-backend:latest .

      - name: Verificar imagen construida
        run: |
          docker images

      - name: Simulación de Push
        run: |
          echo "En el laboratorio el push se realiza al registro local (localhost:5000) desde el servidor k3s."
